name: Test Build

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Uses Node.Js version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Yarn Install
        run: |
          yarn install
      - name: Yarn Test Build
        run: |
          yarn build
      - name: Deployment completed
        env:
          AWS_ACCESS_KEY: "TEST ACCESS KEY"
        run: |
          echo("Test build completed!!")
